# Clean up PR preview environments when PR is closed
name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    name: Cleanup PR Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set up app name
        id: app-name
        run: |
          APP_NAME="engine-pr-${{ github.event.number }}"
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "Cleaning up app: $APP_NAME"

      - name: Check if app exists
        id: app-exists
        run: |
          if flyctl apps list | grep -q "${{ steps.app-name.outputs.app_name }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "App ${{ steps.app-name.outputs.app_name }} does not exist, nothing to clean up"
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Delete fly app
        if: steps.app-exists.outputs.exists == 'true'
        run: |
          flyctl apps destroy "${{ steps.app-name.outputs.app_name }}" --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Comment on PR
        if: steps.app-exists.outputs.exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🗑️ **Preview Environment Cleaned Up**

The preview environment for this PR has been destroyed.

App name: \`${{ steps.app-name.outputs.app_name }}\``
            });