name: PR Preview Deploy
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        id: deploy
        run: |
          APP_NAME="engine-pr-${{ github.event.number }}"
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          
          # Check if app exists, create if not
          if ! flyctl apps list | grep -q "$APP_NAME"; then
            flyctl apps create "$APP_NAME" --org personal
            flyctl config save -a "$APP_NAME"
          fi
          
          # Deploy the app
          flyctl deploy --remote-only --app "$APP_NAME"
          
          # Get the app URL
          APP_URL="https://$APP_NAME.fly.dev"
          echo "app_url=$APP_URL" >> $GITHUB_OUTPUT
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Find existing comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'PR Preview Environment'

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            ## 🚀 PR Preview Environment

            Your PR has been deployed to a preview environment!

            **Preview URL:** ${{ steps.deploy.outputs.app_url }}
            **App Name:** `${{ steps.deploy.outputs.app_name }}`

            This preview will be automatically updated when you push new commits to this PR.
          edit-mode: replace